// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imntfxmbxtxzpoibdyno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbnRmeG1ieHR4enBvaWJkeW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzcyMDYsImV4cCI6MjA2NzExMzIwNn0.X-1cmt92lz6JC_T3TScGasjTBeEHx6nmiaHMLAo6H4o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});